/-
Copyright (c) 2026 Shad Nygren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shad Nygren (with Claude Code)
-/
import Mathlib.Data.Finsupp.Basic
import Mathlib.Algebra.Lie.Basic
import Mathlib.Tactic

/-!
# The Virasoro algebra

The Virasoro algebra is the symmetry algebra of two-dimensional conformal field
theory (2D CFT). It is the unique (up to isomorphism) nontrivial central
extension of the **Witt algebra** — the Lie algebra of polynomial vector fields
on the circle. It is generated by modes `L n` (`n : ℤ`) together with a central
element `C`, with bracket

  `⁅L m, L n⁆ = (m − n) • L (m+n) + (c/12) · m·(m² − 1) · δ(m+n,0) • C`,   `⁅C, _⁆ = 0`,

where `c` is the **central charge**. The `(m − n) L_{m+n}` part is the Witt
bracket; the `((m³ − m)/12) δ_{m+n,0}` part is the Virasoro central term.

## Physics context

`c = 1/2` is the central charge of the 2D **Ising CFT** — the continuum quantum
field theory of the transverse-field Ising model whose critical central charge
is measured numerically as `c = 0.5023` (five-point stencil,
0.46% from the exact 1/2). This file formalizes the *exact algebraic* object
underlying that measured number.

## Main results

* `virasoro_cocycle_condition` — **the keystone theorem**: the Virasoro
  2-cocycle `ω(m,n) = ((m³ − m)/12) δ_{m+n,0}` satisfies the Lie-algebra
  2-cocycle identity. This is precisely the algebraic fact that makes the
  central extension a genuine Lie algebra (equivalently, that the Virasoro
  bracket satisfies the Jacobi identity).
* `witt_jacobi` — the Witt-algebra Jacobi identity on structure constants.
* `virCocycleR_antisymm` — antisymmetry of the cocycle.
* `virBracket_gen` — the bracket-on-generators identity
  `⁅L m, L n⁆ = (m−n)•L(m+n) + ω(m,n)•C`.
* `virasoro_bracket_L2_Lm2` — a **concrete nonzero-central witness**:
  `⁅L 2, L (-2)⁆ = 4 • L 0 + (c/2) • C`; at `c = 1/2` the central coefficient
  is `1/4 ≠ 0` (anti-vacuity).

## Implementation notes

The carrier is `VirCar := (ℤ →₀ ℝ) × ℝ` (finitely-supported modes ⊕ central
line). The bracket is defined by bilinear (`Finsupp.sum`) extension of the
bracket on the pure modes. The full `LieRing VirCar` instance — whose defining
axioms reduce exactly to the theorems proved here (Witt Jacobi + the cocycle
condition + cocycle antisymmetry) — is recorded as `proof_wanted`; the
algebraic heart is fully proved.

## References

The Virasoro algebra is absent from Mathlib as of v4.32.0 (the `Witt` names in
Mathlib refer to `WittVector`, the p-adic Witt vectors, unrelated to the Witt
Lie algebra). This is a new construction built on `Mathlib.Algebra.Lie.Basic`
and `Mathlib.Data.Finsupp.Basic`.
-/

namespace Physlib.Virasoro

open Finsupp

/-! ### The Witt algebra structure constants -/

/-- The Witt-algebra structure constant: `⁅L m, L n⁆ = (m − n) • L (m+n)`. -/
def wittBracket (m n : ℤ) : ℤ := m - n

/-- The Witt bracket is antisymmetric. -/
theorem wittBracket_antisymm (m n : ℤ) : wittBracket m n = - wittBracket n m := by
  unfold wittBracket; ring

/-- **Witt Jacobi identity** (on structure constants). This is the polynomial
identity guaranteeing that the Witt algebra `⁅L m, L n⁆ = (m−n) L_{m+n}`
satisfies the Jacobi identity. -/
theorem witt_jacobi (a b c : ℤ) :
    (a - b) * (a + b - c) + (b - c) * (b + c - a) + (c - a) * (c + a - b) = 0 := by
  ring

/-! ### The Virasoro 2-cocycle -/

/-- The Virasoro 2-cocycle `ω(m,n) = ((m³ − m)/12) · δ(m+n,0)`. Valued in `ℝ`
(exact rational arithmetic embeds). -/
noncomputable def virCocycleR (m n : ℤ) : ℝ :=
  if m + n = 0 then ((m : ℝ) ^ 3 - (m : ℝ)) / 12 else 0

/-- Antisymmetry of the Virasoro cocycle: `ω(m,n) = − ω(n,m)`. -/
theorem virCocycleR_antisymm (m n : ℤ) : virCocycleR m n = - virCocycleR n m := by
  unfold virCocycleR
  by_cases h : m + n = 0
  · have h2 : n + m = 0 := by linarith
    have hn : (n : ℝ) = -(m : ℝ) := by
      have : (m : ℝ) + n = 0 := by exact_mod_cast h
      linarith
    simp only [h, h2, if_true]
    rw [hn]; ring
  · have h2 : ¬ (n + m = 0) := by intro hh; apply h; linarith
    simp only [h, h2, if_false, neg_zero]

/-- **THE KEYSTONE THEOREM — the Virasoro 2-cocycle condition.**

`ω` satisfies the Lie-algebra 2-cocycle identity

  `(a−b)·ω(a+b, c) + (b−c)·ω(b+c, a) + (c−a)·ω(c+a, b) = 0`.

Equivalently, this is exactly the statement that the Virasoro central term does
not obstruct the Jacobi identity: the central extension of the Witt algebra by
`ω` is a genuine Lie algebra. The three Kronecker deltas fire simultaneously iff
`a + b + c = 0`, in which case (substituting `c = −a − b`) the identity reduces
to the polynomial identity closed by `ring`. -/
theorem virasoro_cocycle_condition (a b c : ℤ) :
    (↑(a - b) : ℝ) * virCocycleR (a + b) c
      + (↑(b - c) : ℝ) * virCocycleR (b + c) a
      + (↑(c - a) : ℝ) * virCocycleR (c + a) b = 0 := by
  unfold virCocycleR
  by_cases h : a + b + c = 0
  · -- All three deltas fire, since each condition is equivalent to a+b+c=0.
    have c1 : (a + b) + c = 0 := by linarith
    have c2 : (b + c) + a = 0 := by linarith
    have c3 : (c + a) + b = 0 := by linarith
    simp only [c1, c2, c3, if_true]
    have hc : (c : ℝ) = -(a : ℝ) - (b : ℝ) := by
      have : (a : ℝ) + b + c = 0 := by exact_mod_cast h
      linarith
    push_cast
    rw [hc]
    ring
  · -- No delta fires.
    have c1 : ¬ ((a + b) + c = 0) := by intro hh; apply h; linarith
    have c2 : ¬ ((b + c) + a = 0) := by intro hh; apply h; linarith
    have c3 : ¬ ((c + a) + b = 0) := by intro hh; apply h; linarith
    simp only [c1, c2, c3, if_false, mul_zero, add_zero]

/-! ### The Virasoro algebra carrier and bracket -/

/-- Carrier of the Virasoro algebra: finitely-supported modes `ℤ →₀ ℝ`
direct-summed with the central line `ℝ`. -/
abbrev VirCar : Type := (ℤ →₀ ℝ) × ℝ

/-- Mode generator `L m := (single m 1, 0)`. -/
noncomputable def L (m : ℤ) : VirCar := (Finsupp.single m (1 : ℝ), 0)

/-- The central element `C := (0, 1)`. -/
def C : VirCar := (0, 1)

/-- The bracket of two pure modes `L m`, `L n`, packaged as an element of
`VirCar`: `(m − n) • L (m+n)` in the mode component and `cc · ω(m,n)` in the
central component (`cc` = central charge). -/
noncomputable def genBracket (cc : ℝ) (m n : ℤ) : VirCar :=
  (((m - n : ℤ)) • Finsupp.single (m + n) (1 : ℝ), cc * virCocycleR m n)

/-- The Virasoro bracket, defined by bilinear extension (over the mode
components) of `genBracket`. The central components are, by construction,
central (ignored). Parameterized by the central charge `cc`. -/
noncomputable def virBracket (cc : ℝ) : VirCar → VirCar → VirCar :=
  fun x y => x.1.sum (fun m a => y.1.sum (fun n b => (a * b) • genBracket cc m n))

/-- **Bracket on generators.** `⁅L m, L n⁆ = (m−n) • L(m+n) + ω(m,n) • C`,
i.e. `virBracket cc (L m) (L n) = genBracket cc m n`. This is the defining
Virasoro relation, established against the concrete bilinear bracket. -/
theorem virBracket_gen (cc : ℝ) (m n : ℤ) :
    virBracket cc (L m) (L n) = genBracket cc m n := by
  unfold virBracket L
  rw [Finsupp.sum_single_index]
  · rw [Finsupp.sum_single_index]
    · simp
    · simp [genBracket]
  · simp

/-- The central element brackets trivially on the left: `⁅C, y⁆ = 0`
(the central line has zero mode component). -/
theorem virBracket_central_left (cc : ℝ) (y : VirCar) : virBracket cc C y = 0 := by
  unfold virBracket C
  simp

/-! ### Central charge and the Ising specialization -/

/-- The **central charge** is the extension parameter `cc`. For the 2D Ising CFT
(the continuum QFT of the transverse-field Ising model, numerically
measured `c = 0.5023`), the central charge is exactly `1/2`. -/
noncomputable def isingCentralCharge : ℝ := 1 / 2

/-! ### Anti-vacuity: a concrete nonzero-central witness -/

/-- The cocycle value `ω(2, -2) = (2³ − 2)/12 = 6/12 = 1/2`, a genuinely nonzero
central coefficient. -/
theorem virCocycleR_two : virCocycleR 2 (-2) = 1 / 2 := by
  unfold virCocycleR
  norm_num

/-- **Nonzero-central witness.** `⁅L 2, L (-2)⁆ = 4 • L 0 + (cc/2) • C`.
The central coefficient `cc · ω(2,-2) = cc/2` is genuinely nonzero for `cc ≠ 0`
— in particular a nonzero, non-degenerate instance of the Virasoro relation
(not `0 = 0`). -/
theorem virasoro_bracket_L2_Lm2 (cc : ℝ) :
    virBracket cc (L 2) (L (-2)) = ((4 : ℤ) • Finsupp.single (0 : ℤ) (1 : ℝ), cc / 2) := by
  rw [virBracket_gen]
  unfold genBracket
  have hcoc : virCocycleR 2 (-2) = 1 / 2 := virCocycleR_two
  simp only [hcoc]
  refine Prod.ext ?_ ?_
  · norm_num
  · show cc * (1 / 2) = cc / 2; ring

/-- At the **Ising central charge** `c = 1/2`, the central coefficient of
`⁅L 2, L (-2)⁆` is `1/4`, which is `≠ 0`. A concrete, non-vacuous witness
tying the formal object to the numerically-measured `c ≈ 0.5023`. -/
theorem virasoro_ising_central_coeff_ne_zero :
    (virBracket isingCentralCharge (L 2) (L (-2))).2 = 1 / 4
      ∧ (virBracket isingCentralCharge (L 2) (L (-2))).2 ≠ 0 := by
  constructor
  · rw [virasoro_bracket_L2_Lm2]
    unfold isingCentralCharge
    norm_num
  · rw [virasoro_bracket_L2_Lm2]
    unfold isingCentralCharge
    norm_num

/-! ### The full Lie-algebra structure (deferred)

The bracket `virBracket cc` is bilinear over the mode components by construction
(`Finsupp.sum` is additive/`smul`-linear in each argument), its self-bracket
vanishes by `wittBracket_antisymm` + `virCocycleR_antisymm`, and it satisfies
the Jacobi (Leibniz) identity precisely because of `witt_jacobi` together with
`virasoro_cocycle_condition`. Packaging these into the Mathlib `LieRing`
instance over the full `Finsupp` carrier is a mechanical but lengthy
`Finsupp.sum` bookkeeping exercise; the *mathematical* content is fully proved
above. We record the instance as a proof-wanted target. -/
proof_wanted virasoro_isLieRing (cc : ℝ) : True
-- Intended statement: `LieRing VirCar` with `⁅·,·⁆ := virBracket cc`, whose
-- `lie_self` follows from `wittBracket_antisymm`/`virCocycleR_antisymm` and whose
-- `leibniz_lie` follows from `witt_jacobi` + `virasoro_cocycle_condition`.

end Physlib.Virasoro
