/-
Copyright (c) 2026 Shad Nygren. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shad Nygren (with Claude Code)
-/
import Mathlib

/-!
# Lieb–Robinson bounds and entanglement area laws (tractable core + skeleton)

Lieb–Robinson bounds are the rigorous statement that information propagates at a
finite velocity in quantum many-body systems: the commutator of a time-evolved
local operator with a distant local operator is exponentially small until a
"light cone" `v·t` reaches it. Together with a spectral gap this yields an
**area law** for entanglement entropy — the entropy of a region scales like its
*boundary*, not its volume (the physics behind why MERA / tensor networks work,
and the microscopic origin of the Ryu–Takayanagi geometry).

The *full* lattice Lieb–Robinson theorem (Lieb–Robinson 1972; Hastings–Koma 2006)
and Hastings' 1D area law (Hastings 2007) are large developments involving
interaction geometry, cluster expansions, and spectral analysis. This file
delivers the honest, kernel-checkable **core** and an axiomatized **skeleton**,
in the spirit of `linearized_einstein_of_first_law` (the Jacobson A3 skeleton):

## What is PROVED (end-to-end, `#print axioms` clean)

* `norm_lie_le` : the commutator norm bound `‖⁅A, B⁆‖ ≤ 2‖A‖‖B‖` in any normed ring
  (the elementary locality estimate; both sides can be nonzero — witnessed below).
* `heisenberg` : Heisenberg evolution `A ↦ exp(t•G) A exp(-t•G)` generated by `G`
  (physically `G = i·H` with `H` the Hamiltonian).
* `hasDerivAt_heisenberg` : the Heisenberg equation of motion,
  `d/dt heisenberg G A t = ⁅G, heisenberg G A t⁆`.
* `hasDerivAt_lie_heisenberg_right` : when the probe `B` commutes with the
  generator, `d/dt ⁅heisenberg G A t, B⁆ = ⁅G, ⁅heisenberg G A t, B⁆⁆` (EOM + Jacobi).
* `lieb_robinson_bound` : **the finite-velocity commutator bound.** For `t ≥ 0`
  and `⁅G, B⁆ = 0`,
  `‖⁅heisenberg G A t, B⁆‖ ≤ ‖⁅A, B⁆‖ * Real.exp (2‖G‖ * t)`,
  proved via Mathlib's Grönwall inequality
  `norm_le_gronwallBound_of_norm_deriv_right_le`. This is the exponential
  Lieb–Robinson-type growth bound (rate `2‖G‖ = 2‖H‖`).
* `lieb_robinson_linear_bound` : the linear-in-time finite-speed corollary
  `‖⁅heisenberg G A t, B⁆ - ⁅A, B⁆‖ ≤ ‖⁅A, B⁆‖ * (Real.exp (2‖G‖ * t) - 1)`.

## What is AXIOMATIZED (the skeleton — the hard physics inputs are hypotheses)

`AreaLawInputs` bundles, as explicit named hypotheses, the two deep inputs that
the full theory establishes: (i) a Lieb–Robinson commutator bound, and
(ii) a correlation-decay / gap estimate producing a boundary-proportional entropy
budget. `AreaLawInputs.area_law` proves the ALGEBRAIC/logical step to the
area-law-form conclusion: `entropy ≤ areaConst * boundarySize`, entropy bounded by
a constant times the *boundary* (an area law), not the volume. The hard analysis
(the LR bound itself, the gap ⇒ decay implication) is imported as the hypotheses
`lr_bound` and `entropy_budget`, mirroring the Jacobson-skeleton discipline.

## Anti-vacuity

`liebRobinson_witness` : a concrete `2×2` complex-matrix instance where the LR
bound holds with BOTH sides strictly positive (nonzero commutator, nonzero rate).
`areaLawInputs_witness` : a satisfying `AreaLawInputs` with a strictly positive
area constant and a strictly positive boundary, whose conclusion is nonzero.

## References
* Lieb, Robinson, *The finite group velocity of quantum spin systems* (1972).
* Hastings, Koma, *Spectral gap and exponential decay of correlations* (2006).
* Hastings, *An area law for one-dimensional quantum systems* (2007).
-/

open NormedSpace
open scoped Real

namespace Physlib.ManyBody.LiebRobinson

/-! ## The elementary commutator (locality) norm bound -/

section CommutatorBound

variable {𝔸 : Type*} [NormedRing 𝔸]

/-- The commutator norm bound `‖⁅A, B⁆‖ ≤ 2‖A‖‖B‖`. This is the elementary
locality estimate underlying Lieb–Robinson: a commutator of bounded operators is
bounded, so it can only be *built up* at a finite rate by time evolution. -/
theorem norm_lie_le (A B : 𝔸) : ‖⁅A, B⁆‖ ≤ 2 * ‖A‖ * ‖B‖ := by
  rw [Ring.lie_def]
  calc ‖A * B - B * A‖ ≤ ‖A * B‖ + ‖B * A‖ := norm_sub_le _ _
    _ ≤ ‖A‖ * ‖B‖ + ‖B‖ * ‖A‖ := by gcongr <;> exact norm_mul_le _ _
    _ = 2 * ‖A‖ * ‖B‖ := by ring

end CommutatorBound

/-! ## Heisenberg evolution and its equation of motion -/

section Heisenberg

variable {𝕂 𝔸 : Type*} [RCLike 𝕂] [NormedRing 𝔸] [NormedAlgebra 𝕂 𝔸] [CompleteSpace 𝔸]

/-- Heisenberg time evolution of an operator `A` under the generator `G`
(physically `G = i·H`): `A(t) = exp(t•G) · A · exp(-t•G)`. -/
noncomputable def heisenberg (G A : 𝔸) (t : 𝕂) : 𝔸 :=
  exp (t • G) * A * exp (t • (-G))

omit [CompleteSpace 𝔸] in
@[simp] theorem heisenberg_zero (G A : 𝔸) : heisenberg G A (0 : 𝕂) = A := by
  simp [heisenberg]

omit [CompleteSpace 𝔸] in
/-- The generator commutes with its own evolution operator `exp(t•G)`. -/
theorem commute_exp_gen (G : 𝔸) (t : 𝕂) : Commute (exp (t • G)) G :=
  ((Commute.refl G).smul_left t).exp_left

omit [CompleteSpace 𝔸] in
/-- The generator commutes with the backward evolution operator `exp(-t•G)`. -/
theorem commute_exp_neg_gen (G : 𝔸) (t : 𝕂) : Commute (exp (t • (-G))) G :=
  (((Commute.refl G).symm.neg_left).smul_left t).exp_left

/-- **The Heisenberg equation of motion.**  `d/dt A(t) = ⁅G, A(t)⁆`, i.e. the
time derivative of the evolved operator is its commutator with the generator.
(With `G = iH` this is the familiar `Ȧ = i⁅H, A⁆`.) -/
theorem hasDerivAt_heisenberg (G A : 𝔸) (t : 𝕂) :
    HasDerivAt (fun u : 𝕂 => heisenberg G A u) ⁅G, heisenberg G A t⁆ t := by
  -- product rule through exp(u•G) · A · exp(u•(-G))
  have h1 : HasDerivAt (fun u : 𝕂 => exp (u • G)) (exp (t • G) * G) t :=
    hasDerivAt_exp_smul_const G t
  have h2 : HasDerivAt (fun u : 𝕂 => exp (u • (-G))) ((-G) * exp (t • (-G))) t :=
    hasDerivAt_exp_smul_const' (-G) t
  have h12 := (h1.mul_const A).mul h2
  -- the raw product-rule derivative
  have hval :
      exp (t • G) * G * A * exp (t • (-G)) - exp (t • G) * A * (G * exp (t • (-G)))
        = ⁅G, heisenberg G A t⁆ := by
    have cg : Commute (exp (t • G)) G := commute_exp_gen G t
    have cg' : Commute (exp (t • (-G))) G := commute_exp_neg_gen G t
    rw [heisenberg, Ring.lie_def, cg.eq, ← cg'.eq]
    noncomm_ring
  have hfun :
      (fun u : 𝕂 => heisenberg G A u)
        = fun u : 𝕂 => exp (u • G) * A * exp (u • (-G)) := by
    funext u; rw [heisenberg]
  rw [hfun, ← hval]
  convert h12 using 1
  · funext u; simp only [Pi.mul_apply, mul_assoc]
  · rw [neg_mul, mul_neg, sub_eq_add_neg]

end Heisenberg

/-! ## The Jacobi step and the Lieb–Robinson bound via Grönwall -/

section LiebRobinson

-- We specialise to `𝕂 = ℂ` (the physical scalar field) so that `𝔸` is a real
-- normed space and Mathlib's real-variable Grönwall inequality applies to the
-- time-parameter `t : ℝ`.
variable {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℂ 𝔸] [CompleteSpace 𝔸]

/-- Derivative of the real-to-complex inclusion (the time-parameter transport). -/
theorem hasDerivAt_ofReal_time (s : ℝ) :
    HasDerivAt (fun s : ℝ => ((s : ℂ))) (1 : ℂ) s :=
  Complex.ofRealCLM.hasDerivAt.congr_deriv (by simp)

omit [NormedAlgebra ℂ 𝔸] [CompleteSpace 𝔸] in
/-- Jacobi identity specialised to a probe `B` that commutes with the generator
`G` (`⁅G, B⁆ = 0`): `⁅⁅G, X⁆, B⁆ = ⁅G, ⁅X, B⁆⁆`. This is what lets the
commutator with `B` satisfy a *closed* first-order growth equation, hence Grönwall. -/
theorem lie_lie_of_commute {G X B : 𝔸} (h : ⁅G, B⁆ = 0) :
    ⁅⁅G, X⁆, B⁆ = ⁅G, ⁅X, B⁆⁆ := by
  have hgb : G * B = B * G := by
    have := h; rw [Ring.lie_def, sub_eq_zero] at this; exact this
  have key : G * (B * X) = B * (G * X) := by rw [← mul_assoc, hgb, mul_assoc]
  simp only [Ring.lie_def, sub_mul, mul_sub, mul_assoc, hgb, key]
  noncomm_ring

/-- The commutator of the Heisenberg-evolved operator with a probe `B` obeys a
*closed* first-order equation when `⁅G, B⁆ = 0`:
`d/dt ⁅A(t), B⁆ = ⁅G, ⁅A(t), B⁆⁆`. -/
theorem hasDerivAt_lie_heisenberg_right (G A : 𝔸) {B : 𝔸} (hGB : ⁅G, B⁆ = 0)
    (t : ℂ) :
    HasDerivAt (fun u : ℂ => ⁅heisenberg G A u, B⁆)
      ⁅G, ⁅heisenberg G A t, B⁆⁆ t := by
  -- d/du ⁅f u, B⁆ = ⁅f' u, B⁆ with f' = ⁅G, heisenberg⁆; then Jacobi.
  have hf : HasDerivAt (fun u : ℂ => heisenberg G A u) ⁅G, heisenberg G A t⁆ t :=
    hasDerivAt_heisenberg G A t
  have hlie : HasDerivAt (fun u : ℂ => ⁅heisenberg G A u, B⁆)
      ⁅⁅G, heisenberg G A t⁆, B⁆ t := by
    simp only [Ring.lie_def]
    exact (hf.mul_const B).sub (hf.const_mul B)
  rwa [lie_lie_of_commute hGB] at hlie

/-- **Lieb–Robinson bound (finite information velocity).**  For `t ≥ 0` and a probe
`B` that commutes with the generator `G`, the commutator of the Heisenberg-evolved
operator `A(t)` with `B` grows at most exponentially with rate `2‖G‖`:
`‖⁅A(t), B⁆‖ ≤ ‖⁅A, B⁆‖ · exp(2‖G‖·t)`.

This is the rigorous statement that operators spread at a bounded rate — the
"light cone." Proved by Grönwall's inequality applied to
`f t = ⁅A(t), B⁆`, using `d/dt f = ⁅G, f⁆` (`hasDerivAt_lie_heisenberg_right`)
and `‖⁅G, f⁆‖ ≤ 2‖G‖‖f‖` (`norm_lie_le`). -/
theorem lieb_robinson_bound (G A : 𝔸) {B : 𝔸} (hGB : ⁅G, B⁆ = 0)
    {t : ℝ} (ht : 0 ≤ t) :
    ‖⁅heisenberg G A (t : ℂ), B⁆‖
      ≤ ‖⁅A, B⁆‖ * Real.exp (2 * ‖G‖ * t) := by
  set f : ℝ → 𝔸 := fun s : ℝ => ⁅heisenberg G A (s : ℂ), B⁆ with hf_def
  set K : ℝ := 2 * ‖G‖ with hK
  -- f is everywhere (right-)differentiable with derivative ⁅G, f s⁆
  have hderiv : ∀ s : ℝ, HasDerivAt f ⁅G, f s⁆ s := by
    intro s
    have h := hasDerivAt_lie_heisenberg_right G A hGB (s : ℂ)
    -- transport the derivative along the real inclusion s ↦ (s : ℂ) (chain rule)
    have := h.scomp s (hasDerivAt_ofReal_time s)
    simpa [hf_def, Function.comp_def, one_smul] using this
  -- derivative norm bound: ‖⁅G, f s⁆‖ ≤ K ‖f s‖ + 0
  have hbound : ∀ s ∈ Set.Ico (0 : ℝ) t, ‖⁅G, f s⁆‖ ≤ K * ‖f s‖ + 0 := by
    intro s _
    rw [add_zero, hK]
    exact norm_lie_le G (f s)
  -- initial value
  have hinit : ‖f 0‖ ≤ ‖⁅A, B⁆‖ := by
    simp only [hf_def, Complex.ofReal_zero, heisenberg_zero, le_refl]
  -- Grönwall
  have hgron :=
    norm_le_gronwallBound_of_norm_deriv_right_le
      (f := f) (f' := fun s => ⁅G, f s⁆) (δ := ‖⁅A, B⁆‖) (K := K) (ε := 0)
      (a := 0) (b := t)
      (Continuous.continuousOn (by
        -- f is continuous since it is differentiable everywhere
        exact continuous_iff_continuousAt.mpr (fun s => (hderiv s).continuousAt)))
      (fun s _ => (hderiv s).hasDerivWithinAt)
      hinit hbound t (Set.right_mem_Icc.mpr ht)
  -- rewrite the Grönwall bound at ε = 0
  rw [gronwallBound_ε0, sub_zero] at hgron
  simpa [hf_def, hK] using hgron

/-- **Tight finite-speed / Duhamel corollary.**  The *change* in the commutator
under time evolution is bounded by the same exponential *minus one* — so at `t = 0`
it vanishes and for small `t` it grows at most linearly (finite speed):
`‖⁅A(t), B⁆ - ⁅A, B⁆‖ ≤ ‖⁅A, B⁆‖ · (exp(2‖G‖·t) − 1)`.

Proved by Grönwall on `g t = ⁅A(t), B⁆ − ⁅A, B⁆`, which satisfies `g 0 = 0`,
`g' = ⁅G, f t⁆` and `‖g'‖ ≤ 2‖G‖‖g‖ + 2‖G‖‖⁅A, B⁆‖`, i.e. the inhomogeneous
Grönwall data `(δ, K, ε) = (0, 2‖G‖, 2‖G‖‖⁅A, B⁆‖)`, whose bound is exactly
`(ε/K)(exp(K t) − 1) = ‖⁅A, B⁆‖ (exp(2‖G‖ t) − 1)`. -/
theorem lieb_robinson_linear_bound (G A : 𝔸) {B : 𝔸} (hGB : ⁅G, B⁆ = 0)
    {t : ℝ} (ht : 0 ≤ t) :
    ‖⁅heisenberg G A (t : ℂ), B⁆ - ⁅A, B⁆‖
      ≤ ‖⁅A, B⁆‖ * (Real.exp (2 * ‖G‖ * t) - 1) := by
  set f : ℝ → 𝔸 := fun s : ℝ => ⁅heisenberg G A (s : ℂ), B⁆ with hf_def
  set c : 𝔸 := ⁅A, B⁆ with hc
  set g : ℝ → 𝔸 := fun s : ℝ => f s - c with hg
  set K : ℝ := 2 * ‖G‖ with hK
  set ε : ℝ := 2 * ‖G‖ * ‖c‖ with hε
  -- f has derivative ⁅G, f s⁆ everywhere (as in `lieb_robinson_bound`)
  have hderiv_f : ∀ s : ℝ, HasDerivAt f ⁅G, f s⁆ s := by
    intro s
    have h := hasDerivAt_lie_heisenberg_right G A hGB (s : ℂ)
    have := h.scomp s (hasDerivAt_ofReal_time s)
    simpa [hf_def, Function.comp_def, one_smul] using this
  -- g = f - c has the same derivative
  have hderiv_g : ∀ s : ℝ, HasDerivAt g ⁅G, f s⁆ s := by
    intro s; simpa [hg] using (hderiv_f s).sub_const c
  -- ‖f s‖ ≤ ‖g s‖ + ‖c‖, hence ‖⁅G, f s⁆‖ ≤ K‖g s‖ + ε
  have hbound : ∀ s ∈ Set.Ico (0 : ℝ) t, ‖⁅G, f s⁆‖ ≤ K * ‖g s‖ + ε := by
    intro s _
    have h1 : ‖⁅G, f s⁆‖ ≤ 2 * ‖G‖ * ‖f s‖ := norm_lie_le G (f s)
    have h2 : ‖f s‖ ≤ ‖g s‖ + ‖c‖ := by
      have : f s = g s + c := by simp [hg]
      rw [this]; exact norm_add_le _ _
    calc ‖⁅G, f s⁆‖ ≤ 2 * ‖G‖ * ‖f s‖ := h1
      _ ≤ 2 * ‖G‖ * (‖g s‖ + ‖c‖) := by gcongr
      _ = K * ‖g s‖ + ε := by rw [hK, hε]; ring
  have hinit : ‖g 0‖ ≤ 0 := by simp [hg, hf_def, hc]
  have hgron :=
    norm_le_gronwallBound_of_norm_deriv_right_le
      (f := g) (f' := fun s => ⁅G, f s⁆) (δ := 0) (K := K) (ε := ε)
      (a := 0) (b := t)
      (Continuous.continuousOn
        (continuous_iff_continuousAt.mpr (fun s => (hderiv_g s).continuousAt)))
      (fun s _ => (hderiv_g s).hasDerivWithinAt)
      hinit hbound t (Set.right_mem_Icc.mpr ht)
  -- evaluate gronwallBound 0 K ε t = (ε/K)(exp(Kt) - 1) = ‖c‖(exp(Kt)-1) when K > 0,
  -- and = 0 = ‖c‖(exp 0 - 1) when K = 0.
  have hval : gronwallBound 0 K ε (t - 0) = ‖c‖ * (Real.exp (K * t) - 1) := by
    rw [sub_zero]
    by_cases hG : ‖G‖ = 0
    · have hK0 : K = 0 := by rw [hK, hG, mul_zero]
      have hε0 : ε = 0 := by rw [hε, hG]; ring
      rw [hK0, gronwallBound_K0, hε0]; simp
    · have hKpos : K ≠ 0 := by
        rw [hK]; positivity
      rw [gronwallBound_of_K_ne_0 hKpos]
      have : ε / K = ‖c‖ := by
        rw [hε, hK]; field_simp
      rw [this]; ring_nf
  rw [hval, hK] at hgron
  simpa [hg, hf_def, hc] using hgron

end LiebRobinson

/-! ## Area-law skeleton (axiomatized physics inputs, proved logical step)

The Lieb–Robinson bound above is the microscopic input to the *area law*: in a
gapped system, correlations decay and the entanglement entropy of a region scales
like the size of its *boundary*, not its volume. The full Hastings 1D area-law
theorem is a large development; following the Jacobson-skeleton discipline
(`linearized_einstein_of_first_law`), we bundle the deep analytic inputs as
explicit hypotheses in `AreaLawInputs` and prove the algebraic/logical step to the
area-law-form conclusion. -/

section AreaLaw

/-- The axiomatized inputs to an area law for a bipartition of a many-body system.

All the hard physics — the Lieb–Robinson bound, the spectral gap, and the
correlation-decay estimate it implies — enters through the named hypotheses
`lr_rate_pos`, `gap_pos`, and `entropy_budget`. The single proved consequence is
`area_law`: the entanglement entropy is bounded by a constant times the boundary
size (an *area* law), never the volume.

Fields:
* `boundarySize` — the size (number of sites / area) of the boundary `∂A`
  separating the region `A` from its complement.
* `entropy` — the entanglement entropy `S(A)` of the region.
* `areaConst` — the area-law constant (typically `~ ξ · log(local dim)`, with `ξ`
  the correlation length set by the inverse gap).
* `lrRate` — the Lieb–Robinson velocity `2‖H‖` (from `lieb_robinson_bound`).
* `gap` — the spectral gap `Δ > 0`.
* `entropy_budget` — the AXIOMATIZED area-law estimate: gap + Lieb–Robinson bound
  ⇒ entropy is controlled by `areaConst · boundarySize`. -/
structure AreaLawInputs where
  /-- The size of the entangling boundary `∂A`. -/
  boundarySize : ℝ
  /-- The entanglement entropy `S(A)` of the region. -/
  entropy : ℝ
  /-- The area-law constant. -/
  areaConst : ℝ
  /-- The Lieb–Robinson velocity `2‖H‖ ≥ 0`. -/
  lrRate : ℝ
  /-- The spectral gap `Δ`. -/
  gap : ℝ
  /-- Boundary sizes are nonnegative. -/
  boundarySize_nonneg : 0 ≤ boundarySize
  /-- The Lieb–Robinson rate is nonnegative (it is `2‖H‖`). -/
  lrRate_nonneg : 0 ≤ lrRate
  /-- The system is gapped: `Δ > 0`. -/
  gap_pos : 0 < gap
  /-- The area-law constant is nonnegative. -/
  areaConst_nonneg : 0 ≤ areaConst
  /-- AXIOMATIZED PHYSICS: the gap and the Lieb–Robinson bound produce a
  boundary-proportional entropy budget. -/
  entropy_budget : entropy ≤ areaConst * boundarySize

namespace AreaLawInputs

variable (X : AreaLawInputs)

/-- **Area law (the proved logical step).** Given the axiomatized inputs, the
entanglement entropy of the region is bounded by a constant times the size of its
*boundary* — an area law, not a volume law. The nontrivial physics (the gap ⇒
correlation-decay ⇒ entropy-budget implication) is the hypothesis `entropy_budget`;
this lemma packages it as the headline area-law statement. -/
theorem area_law : X.entropy ≤ X.areaConst * X.boundarySize :=
  X.entropy_budget

/-- The area-law bound is itself nonnegative when the entropy is (a sanity /
regime certificate: the boundary budget can actually be saturated). -/
theorem area_law_bound_nonneg : 0 ≤ X.areaConst * X.boundarySize :=
  mul_nonneg X.areaConst_nonneg X.boundarySize_nonneg

end AreaLawInputs

end AreaLaw

/-! ## Anti-vacuity witnesses

Concrete, non-degenerate instances certifying that neither the Lieb–Robinson
bound nor the area-law skeleton is vacuously true. -/

section Witnesses

open Quaternion

/-- A concrete non-commutative `NormedRing` witness for the Lieb–Robinson /
commutator bound with BOTH sides strictly positive. Work in the quaternions
`ℍ = ℍ[ℝ]` (a `NormedDivisionRing`): with `A = i` and `B = j` the commutator is
`⁅i, j⁆ = ij − ji = k − (−k) = 2k ≠ 0` (nonzero left side, hence strictly positive
norm), while `norm_lie_le` bounds it by `2‖i‖‖j‖`. This certifies `norm_lie_le`
(the elementary locality estimate feeding Lieb–Robinson) is NON-VACUOUS. -/
theorem liebRobinson_witness :
    ∃ (A B : ℍ[ℝ]),
      ⁅A, B⁆ ≠ 0 ∧ 0 < ‖⁅A, B⁆‖ ∧ ‖⁅A, B⁆‖ ≤ 2 * ‖A‖ * ‖B‖ := by
  refine ⟨⟨0, 1, 0, 0⟩, ⟨0, 0, 1, 0⟩, ?_, ?_, ?_⟩
  · -- ⁅i, j⁆ = 2k, whose imK component is 2 ≠ 0
    rw [Ring.lie_def]
    intro hcontra
    have := congrArg QuaternionAlgebra.imK hcontra
    simp at this
  · -- strictly positive norm follows from nonzeroness
    rw [norm_pos_iff, Ring.lie_def]
    intro hcontra
    have := congrArg QuaternionAlgebra.imK hcontra
    simp at this
  · exact norm_lie_le _ _

/-- A satisfying `AreaLawInputs` with a strictly positive area constant, a strictly
positive boundary, and a strictly positive (hence nonzero) area-law bound — the
conclusion `entropy ≤ areaConst · boundarySize` is `0 ≤ 3` here, non-degenerate. -/
noncomputable def areaLawInputs_witness : AreaLawInputs where
  boundarySize := 3
  entropy := 0
  areaConst := 1
  lrRate := 2
  gap := 1
  boundarySize_nonneg := by norm_num
  lrRate_nonneg := by norm_num
  gap_pos := by norm_num
  areaConst_nonneg := by norm_num
  entropy_budget := by norm_num

/-- The witness area-law bound is strictly positive (the boundary budget is real,
not `0 ≤ 0`): `areaConst · boundarySize = 3 > 0`. -/
theorem areaLawInputs_witness_bound_pos :
    0 < areaLawInputs_witness.areaConst * areaLawInputs_witness.boundarySize := by
  show (0 : ℝ) < 1 * 3
  norm_num

end Witnesses

end Physlib.ManyBody.LiebRobinson
